FROM busybox 

COPY ./release/SYSTEM /go/src/PROJ/SYSTEM
COPY ./release/SYSTEM-init-db /go/src/PROJ/SYSTEM-init-db
COPY ./hack/release/config/.backend-config.yaml /go/src/PROJ/config/config.yaml

ENV ConfigPath ./config/config.yaml

RUN mkdir /go/src/PROJ/logs

ADD https://github.com/golang/go/raw/master/lib/time/zoneinfo.zip /usr/local/go/lib/time/zoneinfo.zip

WORKDIR /go/src/PROJ

CMD ["./SYSTEM"]
